/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "colorConvert.h"
/* Header for class com_heng_ku_jnitest_opengl_ColorHelper */

#ifndef _Included_com_heng_ku_jnitest_opengl_ColorHelper
#define _Included_com_heng_ku_jnitest_opengl_ColorHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_heng_ku_jnitest_opengl_ColorHelper
 * Method:    NV21TOYUV420SP
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_NV21TOYUV420SP
        (JNIEnv *env, jclass thiz, jbyteArray srcarray, jbyteArray dstarray, jint ySize) {
    unsigned char *src = (unsigned char *) (*env)->GetByteArrayElements(env, srcarray, 0);
    unsigned char *dst = (unsigned char *) (*env)->GetByteArrayElements(env, dstarray, 0);
    NV21TOYUV420SP(src, dst, ySize);
    (*env)->ReleaseByteArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstarray, dst, JNI_ABORT);
    return;
}

/*
 * Class:     com_heng_ku_jnitest_opengl_ColorHelper
 * Method:    NV21TOYUV420P
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_NV21TOYUV420P
        (JNIEnv *env, jclass thiz, jbyteArray srcarray, jbyteArray dstarray, jint ySize) {
    unsigned char *src = (unsigned char *) (*env)->GetByteArrayElements(env, srcarray, 0);
    unsigned char *dst = (unsigned char *) (*env)->GetByteArrayElements(env, dstarray, 0);
    NV21TOYUV420P(src, dst, ySize);
    (*env)->ReleaseByteArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstarray, dst, JNI_ABORT);
    return;
}
/*
 * Class:     com_heng_ku_jnitest_opengl_ColorHelper
 * Method:    YUV420SPTOYUV420P
 * Signature: ([B[BI)V
 */
JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_YUV420SPTOYUV420P
        (JNIEnv *env, jclass thiz, jbyteArray srcarray, jbyteArray dstarray, jint ySize) {
    unsigned char *src = (unsigned char *) (*env)->GetByteArrayElements(env, srcarray, 0);
    unsigned char *dst = (unsigned char *) (*env)->GetByteArrayElements(env, dstarray, 0);
    YUV420SPTOYUV420P(src, dst, ySize);
    (*env)->ReleaseByteArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstarray, dst, JNI_ABORT);
    return;
}
/*
 * Class:     com_heng_ku_jnitest_opengl_ColorHelper
 * Method:    NV21TOARGB
 * Signature: ([B[III)V
 */
JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_NV21TOARGB
        (JNIEnv *env, jclass thiz, jbyteArray srcarray, jintArray dstarray, jint width,
         jint height) {
    unsigned char *src = (unsigned char *) (*env)->GetByteArrayElements(env, srcarray, 0);
    unsigned int *dst = (unsigned int *) (*env)->GetIntArrayElements(env, dstarray, 0);
    NV21TOARGB(src, dst, width, height);
    (*env)->ReleaseByteArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseIntArrayElements(env, dstarray, dst, JNI_ABORT);
    return;
}
/*
 * Class:     com_heng_ku_jnitest_opengl_ColorHelper
 * Method:    FIXGLPIXEL
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_FIXGLPIXEL
        (JNIEnv *env, jclass thiz, jintArray srcarray, jintArray dstarray, jint w, jint h) {
    unsigned int *src = (unsigned int *) (*env)->GetIntArrayElements(env, srcarray, 0);
    unsigned int *dst = (unsigned int *) (*env)->GetIntArrayElements(env, dstarray, 0);
    FIXGLPIXEL(src, dst, w, h);
    (*env)->ReleaseIntArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseIntArrayElements(env, dstarray, dst, JNI_ABORT);
    return;
}

JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_NV21TOYUV
        (JNIEnv *env, jclass thiz, jbyteArray srcarray, jbyteArray dstYarray, jbyteArray dstUarray,
         jbyteArray dstVarray, jint width, jint height) {
    unsigned char *src = (unsigned char *) (*env)->GetByteArrayElements(env, srcarray, 0);
    unsigned char *dsty = (unsigned char *) (*env)->GetByteArrayElements(env, dstYarray, 0);
    unsigned char *dstu = (unsigned char *) (*env)->GetByteArrayElements(env, dstUarray, 0);
    unsigned char *dstv = (unsigned char *) (*env)->GetByteArrayElements(env, dstVarray, 0);
    NV21TOYUV(src, dsty, dstu, dstv, width, height);
    (*env)->ReleaseByteArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstYarray, dsty, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstUarray, dstu, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstVarray, dstv, JNI_ABORT);
    return;
}
/*
 * Class:     com_heng_ku_jnitest_opengl_ColorHelper
 * Method:    NV21Transform
 * Signature: ([B[BIII)V
 */
JNIEXPORT void JNICALL Java_com_heng_ku_jnitest_opengl_ColorHelper_NV21Transform
        (JNIEnv *env, jclass thiz, jbyteArray srcarray, jbyteArray dstarray, jint srcwidth,
         jint srcheight, jint directionflag) {
    unsigned char *src = (unsigned char *) (*env)->GetByteArrayElements(env, srcarray, 0);
    unsigned char *dst = (unsigned char *) (*env)->GetByteArrayElements(env, dstarray, 0);
    NV21Transform(src, dst, srcwidth, srcheight, directionflag);
    (*env)->ReleaseByteArrayElements(env, srcarray, src, JNI_ABORT);
    (*env)->ReleaseByteArrayElements(env, dstarray, dst, JNI_ABORT);
    return;
}

#ifdef __cplusplus
}
#endif
#endif
